Binomial distribution
InferenceQL/gen.clj pull request #66
Opened 2024-02-27 20:33 UTC by eightysteele

# Purpose

This PR adds support for the binomial distribution. 

# Log-likelihood

The log PMF for the binomial distribution gives the log probability of observing $k$ successes out of $n$ trials:

$P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}$

For computing that binomial coefficient, I used the existing `log-gamma-fn`. Otherwise for large values of $n$ and $k$ it would have overflown on factorials.

# Testing

In `distribution_test.clj` I tested boundary conditions on $n$, $p$, and $k$ and verified some different properties of the distribution that should definitely hold (sum of probabilities, symmetry when $p=0$, mean and variance consistency). Both `bb test:clj` and `bb test:cljs` are passing for these.

I also spot checked a range of values against SciPy and Gen.jl (within a precision threshold of  `1e-9` of expected values). One of theses tests is currently failing because the difference between expected and actual is right at the threshold boundary. If this is problematic, let me know and I can dig in!

```clojure
      ;; TODO: failing test (off by 1.9e-9)
      ;; expected: (ish? -3.222306954272568 (dist/logpdf (->binomial 1000000 0.0001) 100))
      ;; actual: (not (ish? -3.222306954272568 -3.2223069561241857))
      (is (ish? -3.222306954272568 (dist/logpdf (->binomial 1000000 0.0001) 100)))
``` 
# Next steps

A spot check and some feedback would be great. It's entirely possible that I'm missing something here. Happy to make changes.

2024-02-27 20:44 UTC, sritchie requested changes
Nice work, just a few comments!

2024-02-27 20:44 UTC, sritchie commented on src/gen/distribution/java_util.clj
> +    (.nextBinomial rnd n p))
no way, awesome! Is this a thing? I don't see it in the javadocs... https://docs.oracle.com/javase/8/docs/api/java/util/SplittableRandom.html

2024-02-27 20:44 UTC, sritchie commented on src/gen/distribution/math/log_likelihood.cljc
> +  (cond
you might use `case` here to make this more efficient.

2024-02-27 20:44 UTC, sritchie commented on src/gen/distribution/math/log_likelihood.cljc
> +(defn log-bico
let's make this private, or add `^:no-doc` to keep it out of the public API

2024-02-27 20:44 UTC, sritchie commented on src/gen/distribution/math/log_likelihood.cljc
> +(defn log-bico
I would actually make this a local fn with `letfn` instead of making it its own thing. All of these preconditions are going to run every time, if you put it inside `binomial` you can skip running those since you're calling it in a place where you know you pass the preconditions.

2024-02-27 20:44 UTC, sritchie commented on test/gen/distribution_test.cljc
> +    (is ##-Inf(dist/logpdf (->binomial 10 0) 1)))
whoops, missing a space

2024-02-27 20:44 UTC, sritchie commented on test/gen/distribution_test.cljc
> +      (let [n 100
how about making this a generative test? See the `checking` style from other tests.

2024-02-27 20:44 UTC, sritchie commented on test/gen/distribution_test.cljc
> +  (testing "mean and variance consistency where mu = n * p and variance = mu(1 - p)"
can you say more, even if just in comments below, about what you are testing here?

2024-02-27 20:44 UTC, sritchie commented on test/gen/distribution_test.cljc
> +      ;; TODO: failing test (off by 1.9e-9)
delete these if unnecessary

2024-02-29 02:44 UTC, eightysteele commented on src/gen/distribution/math/log_likelihood.cljc
> +  (cond
oh nice, done.

2024-02-29 02:44 UTC, eightysteele commented on src/gen/distribution/math/log_likelihood.cljc
> +(defn log-bico
totally. i made `log-fact` and `log-bico` local with `letfn`.

2024-02-29 02:44 UTC, eightysteele commented on test/gen/distribution_test.cljc
> +    (is ##-Inf(dist/logpdf (->binomial 10 0) 1)))
fixed. should `bb lint` normally catch that?

2024-02-29 02:44 UTC, eightysteele commented on test/gen/distribution_test.cljc
> +      (let [n 100
great idea. i changed a bunch of tests over to generative. done.

2024-02-29 02:44 UTC, eightysteele commented on test/gen/distribution_test.cljc
> +  (testing "mean and variance consistency where mu = n * p and variance = mu(1 - p)"
yeah, i added comments with more context. the basic idea is to spot check a couple of well known properties of the distribution. if that seems weird though i can leave them out for sure.

2024-02-29 02:44 UTC, eightysteele commented on test/gen/distribution_test.cljc
> +      ;; TODO: failing test (off by 1.9e-9)
done. i dialed down the precision threshold from `1e-9` to `1e-6` and all of these tests are now passing. for spot checking against other libraries, that seems like a peaceful threshold but feel free to push back!

2024-02-29 02:44 UTC, eightysteele commented
@sritchie thanks for the fast feedback! just pushed updates and responded to comments.

i took a look at that score function in webppl to see how it compared to the lanczos approximation approach in `log-gamma-fn`:

https://github.com/probmods/webppl/blob/dev/src/dists/binomial.ad.js#L66-L107

i took a quick stab at porting to clojure so that i could run a comparison (this can almost certainly be optimized):

```clojure
(defn binomial
  [n p v]
  {:pre [(integer? n)
         (integer? v)
         (>= v 0)
         (>= n v)
         (<= 0 p 1)]}
  (letfn [(log-fact
            [x]
            (if (< x 2)
              0
              (reduce + (map #(Math/log %) (range 2 (inc x))))))
          (log-bico
            [n m o]
            (let [x (reduce + (map #(Math/log %) (range (inc o) (inc n))))]
              (- x (log-fact m))))]
    (let [[m o] (if (< v (- n v)) [v (- n v)] [(- n v) v])]
      (case p
        0 (if (= v 0)
            0.0     ;; log(1)
            ##-Inf) ;; log(0))
        1 (if (= v n)
            0.0     ;; log(1)
            ##-Inf) ;; log(0)
        (+ (log-bico n m o)
           (* v (Math/log p))
           (* (- n v) (Math/log (- 1 p))))))))
 ```

this particular implementation turned out to be pretty slow with a bit of precision loss as $n$ and $v$ got large (7 minutes to run `bb test:clj` compared to 16 seconds with `log-gamma-fn`).

here's my hypothesis. the runtime complexity of  my original `binomial` is basically $O(1)$, driven by the lanczos approximation in `log-gamma-fn`. that's because it involves a fixed number of coefficients and iterations that do not vary with the input. this is assuming constant time for arithmetic operations.

for the `binomial` test above, the complexity is $O(n)$ from the linear scaling of log summations within the range $n - o$ and the factorial computation $O(m)$. with the optimization to minimize computation range, the worst-case scenario scales linearly with $n$, which bumps the computational cost for larger inputs.

all to say, it seems reasonable to keep the original implementation for now.

2024-02-29 03:03 UTC, eightysteele commented on src/gen/distribution/java_util.clj
> +    (.nextBinomial rnd n p))
(i also added `binomial-gf-tests` that generatively samples from a distribution, which would have caught `.nextBinomial`)

2024-02-29 19:58 UTC, eightysteele commented
purely for my own learning, i worked out a slightly more efficient implementation that memoizes factorials and swaps map/reduce for loop/recur (to factor out intermediate collections). it's roughly 78% faster than that first version, but still a minute slower than the `log-gamma-fn` version. 

```clojure
(def memoized-log-fact
  (memoize
   (fn [x]
     (loop [i x
            acc 0.0]
       (if (< i 2)
         acc
         (recur (dec i) (+ acc (Math/log i))))))))

(defn log-bico
  [n m o]
  (let [numerator (loop [i (inc o)
                         acc 0.0]
                    (if (> i n)
                      acc
                      (recur (inc i) (+ acc (Math/log i)))))]
    (- numerator (memoized-log-fact m))))

(defn binomial
  [n p v]
  {:pre [(integer? n)
         (integer? v)
         (>= v 0)
         (>= n v)
         (<= 0 p 1)]}
  (let [[m o] (if (< v (- n v)) [v (- n v)] [(- n v) v])]
    (case p
      0 (if (= v 0) 0.0 ##-Inf)
      1 (if (= v n) 0.0 ##-Inf)
      (+ (log-bico n m o)
         (* v (Math/log p))
         (* (- n v) (Math/log (- 1 p)))))))
'''

2024-03-12 21:27 UTC, sritchie commented on src/gen/distribution/math/log_likelihood.cljc
> +  {:pre [(integer? n)
I think in ClojureScript, `number?` checks if you have a `goog.math/Integer`... is that right? I want to check on how we did this in Emmy, I feel like there is some other predicate we should use. I could be wrong, flying blind here before a meeting..

2024-03-12 21:28 UTC, sritchie commented on test/gen/distribution_test.cljc
> +    (is ##-Inf(dist/logpdf (->binomial 10 0) 1)))
looks like it's still there, I'm not sure, maybe it should?

2024-03-12 22:31 UTC, sritchie approved these changes

2024-03-12 22:31 UTC, sritchie commented
Thanks @eightysteele , this looks great!!

2024-03-12 22:31 UTC, merged

2024-03-13 00:08 UTC, eightysteele commented on src/gen/distribution/math/log_likelihood.cljc
> +  {:pre [(integer? n)
yeah not sure, but it doesn't look like cljs checks for `goog.math/Integer`:

https://github.com/clojure/clojurescript/blob/acbefb9b1e79b659b639919fbf96cb3726719e25/src/main/cljs/cljs/core.cljs#L2328-L2334

in emmy i don't see an `integer?` defined, but the value namespace does have predicates like `real?` and `number?` that do use `goog.math/...`:

https://github.com/mentat-collective/emmy/blob/main/src/emmy/value.cljc 

BUT if i understand the compatibility layer between clj and cljs, if we use integer? in clojure code and then compile it to cljs, the cljs version of integer? should be used when the code runs in a js environment. if that's the case, then it's plausible that this is the right predicate to use?

2024-03-13 00:08 UTC, eightysteele commented
thanks @sritchie! \o/